# Generated by Django 4.2.13 on 2024-09-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
