# Generated by Django 4.2.13 on 2024-09-12 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('tick', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('volume', models.BigIntegerField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_shares', models.BigIntegerField()),
                ('list_date', models.DateField()),
                ('stock_type', models.CharField(choices=[('TECH', 'Technology'), ('HEAL', 'Healthcare'), ('FIN', 'Finance'), ('ENER', 'Energy'), ('CG', 'Consumer Goods'), ('UTIL', 'Utilities'), ('MATE', 'Materials'), ('IND', 'Industrials'), ('TEL', 'Telecommunications')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tick'],
                'indexes': [models.Index(fields=['tick', '-list_date', 'currency'], name='stocks_stoc_tick_7066dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_logs', to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'indexes': [models.Index(fields=['-created_at', '-new_price', 'old_price'], name='stocks_pric_created_ecedec_idx')],
            },
        ),
    ]
